# Generated by Marten 0.5.2 on 2024-09-21 14:55:33 +03:00

class Migration::Main::V202409211455331 < Marten::Migration
  def plan
    create_table :main_custom_duty_hs_section do
      column :id, :string, max_size: 255, primary_key: true
      column :name_en, :string, max_size: 255
      column :name_ckb, :string, max_size: 255
      column :name_ar, :string, max_size: 255
      column :code, :string, max_size: 10
    end
  end
end
