# Generated by Marten 0.5.2 on 2024-09-22 00:41:58 +03:00

class Migration::Main::V202409220041581 < Marten::Migration
  depends_on :main, "202409220035051_create_main_custom_duty_hs_section_table"

  def plan
    change_column :main_custom_duty_hs_section, :name_en, :string, max_size: 255, unique: true

    add_index :main_custom_duty_hs_section, :name_en_unique_index, [:name_en]
  end
end
